### ISSUE TITLE
DE10-Nano: boot loop

### ISSUE THREAD

**Issue by t-legiaw** [robseb/rsyocto#5]
Hi Robin,

I am facing a boot loop ...

env ...

Board: DE10-Nano
SD Card Image: rsYocto Vers. 1.03 (build 10.01.2020)

Symptom ...

seems to work fine and boots the linux kernel until it comes to the modules stuff where it says

` depmod: ERROR: could not open directory /lib/modules/5.4.0-altera: No such file or directory`

After that it does some other stuff, e.g. getting an IP (DHCP) and time sync works correctly anyway, but there is no login prompt offering a root console.

The final message is  `Time sync. done`. 

Then after some seconds it goes into a boot loop and the same things appear over and over again.

regards - Hans

**Comment by t-legiaw** [comment]
see attached serial console output ...
[rsYocto.txt](https://github.com/robseb/rsyocto/files/4150105/rsYocto.txt)

**Comment by robseb** [comment]
Hi Hans,
thanks for your issue request!
At first glance it looks like a problem with the image file itself. 
Please try to redownload the image file again and flash it again onto a SD-Card.
Check if your SD Card is supported. Class 4 and 10 Micro SD-Cards work property. I think SD-Cards with more than 32 GB are not supported by the SDIO Controller.


Best regards
Robin

**Comment by robseb** [comment]
Hi Hans,
thanks for your issue request!
At first glance it looks like a problem with the image file itself. 
Please try to redownload the image file again and flash it again onto a SD-Card.
Check if your SD Card is supported. Class 4 and 10 Micro SD-Cards work property. I think SD-Cards with more than 32 GB are not supported by the SDIO Controller.


Best regards
Robin

**Comment by robseb** [comment]
Hi Hans,
thanks for your issue request!
I was able to reproduce your issue. 
I think your problem is that the MSEL switch of your board is not in the correct position. 
After the boot is complete starts rsYocto an startup script. 
This script reads in the first step the current date and then puts an FPGA LED on the board on. 
In case the Lightweight HPS to FPGA Bridge is disabled is a MPU event triggert and the watshdog restarts the board again. 
On Cyclone V FPGAs must be the brige enabled with the MSEL as shown in my getting started guide. The here conflicting shell script is shown at the end of guide 6. 

During the boot should u-boot write an LED pattern to the FPGA LEDs of the board!

Best regards 
Robin Sebastian

**Comment by t-legiaw** [comment]
ah - I see ... definitely my own fault ...

sorry for bothering you. Everything is working fine now.

+I really appreciate your help :-)
